services:
  mysql8-container:
    container_name: mysql123
    image: mysql:8.3.0    
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: myapp
    ports:
      - 3306:3306
    #volumes: 
    #- ./sql/myapp.sql:/docker-entrypoint-initdb.d/init-script.sql
    networks:
      - phi-app-network  

  phpmyadmin8-container:
    #intel host
    image: phpmyadmin:latest
    #image: arm64v8/phpmyadmin #choose this if you are running on Mac Apple Silicon(M1, M2,...)
    container_name: phpmyadmin8-container
    restart: always
    depends_on:
      - mysql8-container
    ports:
      - "80:80" #port mapping
    environment:
      PMA_HOST: mysql123 #phpMyAdmin Host, PMA = PHP My Amin
      PMA_PORT: 3306
      UPLOAD_LIMIT: 500M
    networks:
      - phi-app-network

networks:
  phi-app-network:
    name: phi-app-network
    driver: bridge